const SIGNATURE_DISHES: Record<string, string> = {
  "Applebee's": "Bourbon Street Steak",
  "Arby's": "Classic Roast Beef Sandwich",
  "Au Bon Pain": "Chicken Caesar on Asiago Bagel",
  "Bahama Breeze": "Jerk Chicken Pasta",
  "Baja Fresh": "Bare Burrito with Steak",
  "Baskin-Robbins": "Pralines 'n Cream Ice Cream",
  Benihana: "Hibachi Chicken Fried Rice",
  "BJ's Restaurant & Brewhouse": "Deep Dish Pepperoni Pizza",
  "Blaze Pizza": "Red Vine Pizza",
  Bojangles: "Cajun Chicken Biscuit",
  "Bonefish Grill": "Bang Bang Shrimp",
  "Boston Market": "Rotisserie Chicken Meal",
  "Buffalo Wild Wings": "Honey BBQ Wings",
  "Burger King": "Whopper",
  "Cafe Rio": "Sweet Pork Burrito",
  "California Pizza Kitchen": "BBQ Chicken Pizza",
  "Captain D's": "Fish and Fries Combo",
  "Caribou Coffee": "Northern Lite Latte",
  "Carl's Jr.": "Famous Star with Cheese",
  "Carrabba's Italian Grill": "Chicken Bryan",
  Cava: "Harissa Honey Chicken Bowl",
  Checkers: "Baconzilla Burger",
  "The Cheesecake Factory": "Louisiana Chicken Pasta",
  "Chick-fil-A": "Spicy Chicken Sandwich",
  "Chicken Express": "Tender Combo",
  "Chili's": "Baby Back Ribs",
  Chipotle: "Chicken Burrito Bowl",
  "Church's Chicken": "Spicy Tender Combo",
  Cinnabon: "Classic Cinnamon Roll",
  "Cold Stone Creamery": "Birthday Cake Remix",
  "Cook Out": "Cook Out Tray with Big Double Burger",
  "Corner Bakery Cafe": "Chicken Pomodori Panini",
  "Costa Vida": "Sweet Pork Enchilada",
  "Cracker Barrel": "Country Fried Steak",
  "Culver's": "ButterBurger with Cheese",
  "Dairy Queen": "Blizzard Oreo",
  "Dave & Buster's": "Classic Cheeseburger",
  "Del Taco": "Del Combo Burrito",
  "Denny's": "Grand Slam Breakfast",
  "Domino's": "ExtravaganZZa Pizza",
  "Dunkin'": "Iced Caramel Latte",
  "Einstein Bros. Bagels": "Nova Lox Bagel",
  "El Pollo Loco": "Double Chicken Avocado Burrito",
  "Fazoli's": "Baked Spaghetti",
  "Firehouse Subs": "Hook and Ladder Sub",
  "Five Guys": "Cheeseburger with Cajun Fries",
  "Freddy's Frozen Custard": "Double Steakburger",
  "Golden Corral": "Carved Sirloin Steak",
  "Great American Cookies": "Chocolate Chip Cookie Cake",
  "Hardee's": "Frisco Breakfast Sandwich",
  Hooters: "10-Piece Traditional Wings",
  "Huddle House": "All Star Breakfast Plate",
  IHOP: "Original Buttermilk Pancakes",
  "In-N-Out Burger": "Double-Double",
  "Jack in the Box": "Jumbo Jack",
  "Jason's Deli": "California Club Wrap",
  "Jersey Mike's Subs": "Mike's Way Italian Sub",
  "Jimmy John's": "Beach Club Sandwich",
  "Joe's Crab Shack": "Steampot for Two",
  KFC: "Original Recipe Chicken Bucket",
  "Krispy Kreme": "Original Glazed Doughnut",
  Krystal: "Krystal Sackful",
  "La Madeleine": "Country French Breakfast",
  "Little Caesars": "Hot-N-Ready Pepperoni Pizza",
  "LongHorn Steakhouse": "Flo's Filet",
  "Maggiano's Little Italy": "Lasagna Classico",
  "Marco's Pizza": "All Meat Pizza",
  "McAlister's Deli": "Spud Max",
  "McDonald's": "Big Mac",
  "Mellow Mushroom": "Holy Shiitake Pizza",
  "Moe's Southwest Grill": "Homewrecker Burrito",
  "Mooyah Burgers": "Classic Mooyah Burger",
  "Mortons The Steakhouse": "Center-Cut Filet Mignon",
  "Nando's": "Flame-Grilled Peri-Peri Chicken",
  "Noodles & Company": "Wisconsin Mac and Cheese",
  "O'Charley's": "Loaded Chicken Tenders",
  "Olive Garden": "Tour of Italy",
  "On the Border": "Dos XX Fish Tacos",
  "Outback Steakhouse": "Bloomin' Onion and Ribeye",
  "P.F. Chang's": "Mongolian Beef",
  "Panda Express": "Orange Chicken",
  "Panera Bread": "Broccoli Cheddar Soup in Bread Bowl",
  "Papa John's": "The Works Pizza",
  "Papa Murphy's": "Cowboy Pizza",
  "Peet's Coffee": "Caffe Latte",
  "Pei Wei Asian Kitchen": "Kung Pao Chicken",
  "Perkins Restaurant & Bakery": "Mammoth Muffin Breakfast",
  "Peter Piper Pizza": "All Meat Pizza",
  "Pizza Hut": "Meat Lover's Pizza",
  "Pizza Inn": "Hometown Classic Pizza",
  "Pollo Tropical": "TropiChop with Mojo Chicken",
  Popeyes: "Chicken Sandwich",
  "Potbelly Sandwich Shop": "A Wreck Sandwich",
  Qdoba: "Chicken Protein Bowl",
  Quiznos: "Classic Italian Sub",
  "Raising Cane's": "Box Combo",
  "Rally's": "Baconzilla",
  "Red Lobster": "Ultimate Feast",
  "Red Robin": "Royal Red Robin Burger",
  "Romano's Macaroni Grill": "Chicken Parmesan",
  "Round Table Pizza": "King Arthur's Supreme Pizza",
  "Ruby Tuesday": "Ribeye Steak",
  "Ruth's Chris Steak House": "New York Strip",
  Saladworks: "Honey Crisp Chicken Salad",
  "Schlotzsky's": "The Original Sandwich",
  "Shake Shack": "ShackBurger",
  "Shoney's": "All American Breakfast",
  Smashburger: "Classic Smashburger",
  "Smoothie King": "Hulk Chocolate Smoothie",
  "Sonic Drive-In": "SuperSONIC Cheeseburger",
  Starbucks: "Iced Brown Sugar Oatmilk Shaken Espresso",
  "Steak 'n Shake": "Original Double Steakburger",
  Subway: "Italian B.M.T. Footlong",
  Sweetgreen: "Harvest Bowl",
  "Taco Bell": "Crunchwrap Supreme",
  "Taco Cabana": "Brisket Taco Plate",
  "Taco John's": "Six-Pack and a Pound",
  "Texas Roadhouse": "Hand-Cut Ribeye",
  "TGI Fridays": "Jack Daniel's Ribs",
  "The Habit Burger Grill": "Charburger with Double Patty",
  "Tim Hortons": "Double Double Coffee",
  "Torchy's Tacos": "Trailer Park Taco",
  "Twin Peaks": "Pork Belly Bites",
  "Waffle House": "All-Star Special",
  "Wendy's": "Baconator",
  Whataburger: "Whataburger with Cheese",
  "Which Wich": "Wicked Melt",
  "White Castle": "Original Slider Combo",
  Wingstop: "Lemon Pepper Wings",
  "Yard House": "Poke Nachos",
  "Zaxby's": "Chicken Finger Plate",
  "Zoe's Kitchen": "Chicken Kabobs",
};

const GENERIC_DISH_PATTERNS = [
  /^signature\b/i,
  /^house special$/i,
  /^chef'?s?\s+(special|pick)$/i,
  /^local favorite$/i,
  /^popular (item|pick)$/i,
  /^menu favorite$/i,
  /^must[- ]try$/i,
  /^classic dish$/i,
  /^house favorite$/i,
];

export function isGenericDishName(dish: string) {
  const trimmed = dish.trim();
  if (!trimmed) return true;
  return GENERIC_DISH_PATTERNS.some((pattern) => pattern.test(trimmed));
}

export function getSignatureDish(restaurant: string) {
  const exact = SIGNATURE_DISHES[restaurant];
  if (exact) return exact;

  const lower = restaurant.toLowerCase();
  if (lower.includes("pizza")) return "Pepperoni Pizza";
  if (lower.includes("coffee") || lower.includes("dunkin") || lower.includes("peet")) {
    return "Iced Latte";
  }
  if (lower.includes("taco")) return "Street Tacos";
  if (lower.includes("wing")) return "Buffalo Wings";
  if (lower.includes("burger") || lower.includes("shake")) return "Classic Cheeseburger";
  if (lower.includes("sushi") || lower.includes("benihana")) return "Chicken Teriyaki";
  if (lower.includes("steak")) return "Ribeye Steak";
  if (lower.includes("cookie") || lower.includes("cinnabon")) return "Chocolate Chip Cookie";
  if (lower.includes("ice cream") || lower.includes("custard") || lower.includes("dairy queen")) {
    return "Vanilla Sundae";
  }

  return "Grilled Chicken Plate";
}
